version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "1337:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
