version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=root
    ports:
      - "5556:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
